# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI-x86_x64

on: 
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: 
      - openwrt-23.05
    
  # schedule:
  #   - cron: 0 20 * * *

permissions:
  contents: read

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt update
          sudo -E apt -y upgrade
          sudo -E apt -y install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: Update feeds
        run: |
          echo "src-git kiddin9 https://github.com/kiddin9/openwrt-packages.git" >> ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_GRUB_TIMEOUT="1"
          CONFIG_TARGET_KERNEL_PARTSIZE=128
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          CONFIG_VHDX_IMAGES=y
          CONFIG_ZSTD_OPTIMIZE_O3=y
          CONFIG_shadow-all=y
          # CONFIG_SIGNATURE_CHECK is not set
          CONFIG_PACKAGE_TAR_BZIP2=y
          CONFIG_PACKAGE_TAR_GZIP=y
          CONFIG_PACKAGE_TAR_XZ=y
          CONFIG_PACKAGE_TAR_ZSTD=y
          CONFIG_PACKAGE_UnblockNeteaseMusic-Go=y
          CONFIG_PACKAGE_adguardhome=y
          CONFIG_PACKAGE_alist=y
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_attr=y
          CONFIG_PACKAGE_avahi-dbus-daemon=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_blkid=y
          CONFIG_PACKAGE_block-mount=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-system=y
          CONFIG_PACKAGE_bzip2=y
          CONFIG_PACKAGE_cgi-io=y
          CONFIG_PACKAGE_chinadns-ng=y
          CONFIG_PACKAGE_coreutils=y
          CONFIG_PACKAGE_coreutils-base64=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_coreutils-stat=y
          CONFIG_PACKAGE_coreutils-stty=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_dbus=y
          CONFIG_PACKAGE_ddns-scripts=y
          CONFIG_PACKAGE_ddns-scripts-cloudflare=y
          CONFIG_PACKAGE_ddns-scripts-services=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_dns2tcp=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_dnsmasq_full_auth=y
          CONFIG_PACKAGE_dnsmasq_full_conntrack=y
          CONFIG_PACKAGE_dnsmasq_full_dhcp=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_dnsmasq_full_dnssec=y
          CONFIG_PACKAGE_dnsmasq_full_nftset=y
          CONFIG_PACKAGE_dnsmasq_full_noid=y
          CONFIG_PACKAGE_dnsmasq_full_tftp=y
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_etherwake=y
          CONFIG_PACKAGE_filebrowser=y
          CONFIG_PACKAGE_fuse-overlayfs=y
          CONFIG_PACKAGE_fuse-utils=y
          CONFIG_PACKAGE_fuse3-utils=y
          CONFIG_PACKAGE_haproxy=y
          CONFIG_PACKAGE_intel-microcode=y
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-iprange=y
          CONFIG_PACKAGE_iptables-mod-socket=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          # CONFIG_PACKAGE_kmod-e1000e is not set
          CONFIG_PACKAGE_kmod-fuse=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-ipt-conntrack=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-iprange=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-socket=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-md-raid0=y
          CONFIG_PACKAGE_kmod-md-raid1=y
          CONFIG_PACKAGE_kmod-md-raid10=y
          CONFIG_PACKAGE_kmod-nf-conncount=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-nf-socket=y
          CONFIG_PACKAGE_kmod-nft-socket=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_kmod-usb-storage-uas=y
          CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libavahi-client=y
          CONFIG_PACKAGE_libavahi-dbus-support=y
          CONFIG_PACKAGE_libbpf=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcares=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libdaemon=y
          CONFIG_PACKAGE_libdbus=y
          CONFIG_PACKAGE_libelf=y
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libexpat=y
          CONFIG_PACKAGE_libfuse=y
          CONFIG_PACKAGE_libfuse3=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_libiwinfo=y
          CONFIG_PACKAGE_libiwinfo-data=y
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_liblua=y
          CONFIG_PACKAGE_liblua5.3=y
          CONFIG_PACKAGE_liblucihttp=y
          CONFIG_PACKAGE_liblucihttp-lua=y
          CONFIG_PACKAGE_liblucihttp-ucode=y
          CONFIG_PACKAGE_liblzma=y
          CONFIG_PACKAGE_libmaxminddb=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libnetfilter-conntrack=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnfnetlink=y
          CONFIG_PACKAGE_libnghttp2=y
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_libparted=y
          CONFIG_PACKAGE_libpcre=y
          CONFIG_PACKAGE_libpcre2=y
          CONFIG_PACKAGE_libpopt=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libtasn1=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_libubus-lua=y
          CONFIG_PACKAGE_libuci-lua=y
          CONFIG_PACKAGE_libudns=y
          CONFIG_PACKAGE_liburing=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libxtables=y
          CONFIG_PACKAGE_libzstd=y
          CONFIG_PACKAGE_lsblk=y
          CONFIG_PACKAGE_lua=y
          CONFIG_PACKAGE_lua-maxminddb=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-alist=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-filebrowser=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-istorex=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall2=y
          CONFIG_PACKAGE_luci-app-passwall2_Nftables_Transparent_Proxy=y
          CONFIG_PACKAGE_luci-app-passwall_Nftables_Transparent_Proxy=y
          CONFIG_PACKAGE_luci-app-quickstart=y
          CONFIG_PACKAGE_luci-app-rclone=y
          CONFIG_PACKAGE_luci-app-samba4=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-store=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-unishare=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-alist-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-autoreboot-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-diskman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filebrowser-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filetransfer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-quickstart-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-rclone-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unblockmusic-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vlmcsd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
          CONFIG_PACKAGE_luci-lib-base=y
          CONFIG_PACKAGE_luci-lib-docker=y
          CONFIG_PACKAGE_luci-lib-fs=y
          CONFIG_PACKAGE_luci-lib-ip=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_luci-lib-jsonc=y
          CONFIG_PACKAGE_luci-lib-nixio=y
          CONFIG_PACKAGE_luci-lib-taskd=y
          CONFIG_PACKAGE_luci-lib-xterm=y
          CONFIG_PACKAGE_luci-light=y
          CONFIG_PACKAGE_luci-lua-runtime=y
          CONFIG_PACKAGE_luci-mod-admin-full=y
          CONFIG_PACKAGE_luci-mod-network=y
          CONFIG_PACKAGE_luci-mod-status=y
          CONFIG_PACKAGE_luci-mod-system=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_mdadm=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_mmdvm-luci-i18n-zh-cn=y
          CONFIG_PACKAGE_mount-utils=y
          CONFIG_PACKAGE_parted=y
          CONFIG_PACKAGE_quickstart=y
          CONFIG_PACKAGE_rclone=y
          CONFIG_PACKAGE_rclone-config=y
          CONFIG_PACKAGE_rclone-ng=y
          CONFIG_PACKAGE_rclone-webui-react=y
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_rpcd=y
          CONFIG_PACKAGE_rpcd-mod-file=y
          CONFIG_PACKAGE_rpcd-mod-iwinfo=y
          CONFIG_PACKAGE_rpcd-mod-luci=y
          CONFIG_PACKAGE_rpcd-mod-rrdns=y
          CONFIG_PACKAGE_rpcd-mod-ucode=y
          CONFIG_PACKAGE_samba4-libs=y
          CONFIG_PACKAGE_samba4-server=y
          CONFIG_PACKAGE_script-utils=y
          CONFIG_PACKAGE_shadow=y
          CONFIG_PACKAGE_shadow-chage=y
          CONFIG_PACKAGE_shadow-chfn=y
          CONFIG_PACKAGE_shadow-chgpasswd=y
          CONFIG_PACKAGE_shadow-chpasswd=y
          CONFIG_PACKAGE_shadow-chsh=y
          CONFIG_PACKAGE_shadow-common=y
          CONFIG_PACKAGE_shadow-expiry=y
          CONFIG_PACKAGE_shadow-faillog=y
          CONFIG_PACKAGE_shadow-gpasswd=y
          CONFIG_PACKAGE_shadow-groupadd=y
          CONFIG_PACKAGE_shadow-groupdel=y
          CONFIG_PACKAGE_shadow-groupmems=y
          CONFIG_PACKAGE_shadow-groupmod=y
          CONFIG_PACKAGE_shadow-groups=y
          CONFIG_PACKAGE_shadow-grpck=y
          CONFIG_PACKAGE_shadow-grpconv=y
          CONFIG_PACKAGE_shadow-grpunconv=y
          CONFIG_PACKAGE_shadow-lastlog=y
          CONFIG_PACKAGE_shadow-login=y
          CONFIG_PACKAGE_shadow-logoutd=y
          CONFIG_PACKAGE_shadow-newgidmap=y
          CONFIG_PACKAGE_shadow-newgrp=y
          CONFIG_PACKAGE_shadow-newuidmap=y
          CONFIG_PACKAGE_shadow-newusers=y
          CONFIG_PACKAGE_shadow-nologin=y
          CONFIG_PACKAGE_shadow-passwd=y
          CONFIG_PACKAGE_shadow-pwck=y
          CONFIG_PACKAGE_shadow-pwconv=y
          CONFIG_PACKAGE_shadow-pwunconv=y
          CONFIG_PACKAGE_shadow-su=y
          CONFIG_PACKAGE_shadow-useradd=y
          CONFIG_PACKAGE_shadow-userdel=y
          CONFIG_PACKAGE_shadow-usermod=y
          CONFIG_PACKAGE_shadow-utils=y
          CONFIG_PACKAGE_shadow-vipw=y
          CONFIG_PACKAGE_shadowsocks-libev-config=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
          CONFIG_PACKAGE_simple-obfs=y
          CONFIG_PACKAGE_sing-box=y
          CONFIG_PACKAGE_smartd=y
          CONFIG_PACKAGE_smartdns=y
          CONFIG_PACKAGE_smartmontools=y
          CONFIG_PACKAGE_tar=y
          CONFIG_PACKAGE_taskd=y
          CONFIG_PACKAGE_tcping=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_trojan-plus=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_ucode-mod-html=y
          CONFIG_PACKAGE_ucode-mod-lua=y
          CONFIG_PACKAGE_ucode-mod-math=y
          CONFIG_PACKAGE_uhttpd=y
          CONFIG_PACKAGE_uhttpd-mod-ubus=y
          CONFIG_PACKAGE_unishare=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_v2ray-geoip=y
          CONFIG_PACKAGE_v2ray-geosite=y
          CONFIG_PACKAGE_v2ray-plugin=y
          CONFIG_PACKAGE_vlmcsd=y
          CONFIG_PACKAGE_webdav2=y
          CONFIG_PACKAGE_wget-ssl=y
          CONFIG_PACKAGE_wsdd2=y
          CONFIG_PACKAGE_xray-core=y
          CONFIG_PACKAGE_xz=y
          CONFIG_PACKAGE_xz-utils=y
          CONFIG_PACKAGE_zlib=y
          CONFIG_PARTED_READLINE=y
          CONFIG_PCRE2_JIT_ENABLED=y
          CONFIG_PCRE_JIT_ENABLED=y
          CONFIG_SAMBA4_SERVER_AVAHI=y
          CONFIG_SAMBA4_SERVER_NETBIOS=y
          CONFIG_SAMBA4_SERVER_VFS=y
          CONFIG_SAMBA4_SERVER_WSDD2=y
          CONFIG_SINGBOX_WITH_CLASH_API=y
          CONFIG_SINGBOX_WITH_ECH=y
          CONFIG_SINGBOX_WITH_GVISOR=y
          CONFIG_SINGBOX_WITH_QUIC=y
          CONFIG_SINGBOX_WITH_REALITY_SERVER=y
          CONFIG_SINGBOX_WITH_UTLS=y
          CONFIG_SINGBOX_WITH_WIREGUARD=y
          CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-alist-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-autoreboot-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-diskman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filebrowser-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filetransfer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-quickstart-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-rclone-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unblockmusic-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vlmcsd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
          EOF
          make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        run: |
          make -j$(nproc) V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
